kind = "api"
previewPath = "/api"
title = "Discord Bot"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "Discord Bot"
paths = ["/api"]

[services.development]
run = "pnpm --filter @workspace/discord-bot run dev"

[services.production]

[services.production.run]
args = ["node", "artifacts/api-server/src/index.js"]

[services.production.run.env]
NODE_ENV = "production"
